// @vitest-environment node
//
// Drift detection tests. The git-backed probes (buildSourceHead, commitGap) run
// against REAL throwaway repos created in tmp — the whole point of this module
// is that its answers come from git, so mocking git out would test nothing.
// The docker probes are mocked at the DockerService seam.
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import fs from 'fs'
import os from 'os'
import path from 'path'
import { execFileSync } from 'child_process'
import {
  BUILD_SHA_PATH,
  AGENT_CODE_PATH,
  buildSourceHead,
  commitGap,
  containerBuildSha,
  hotPatched,
  readComposeService,
  driftTargets,
  resolveBuildSourceDir,
  driftForTarget,
  fleetDrift,
  harnessIdForName,
  type DriftTarget,
} from '../drift'
import type { Harness } from '@/lib/types'

// --- helpers ---------------------------------------------------------------

function git(dir: string, args: string[]): string {
  return execFileSync('git', ['-C', dir, ...args], {
    stdio: 'pipe',
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: 'T',
      GIT_AUTHOR_EMAIL: 't@example.com',
      GIT_COMMITTER_NAME: 'T',
      GIT_COMMITTER_EMAIL: 't@example.com',
    },
  })
    .toString()
    .trim()
}

/** A repo with `n` commits, each stamped `dayStep` days apart. */
function makeRepo(root: string, n: number, dayStep = 1): { dir: string; shas: string[] } {
  const dir = fs.mkdtempSync(path.join(root, 'src-'))
  execFileSync('git', ['init', '-q', '-b', 'main', dir], { stdio: 'pipe' })
  const shas: string[] = []
  const base = Date.parse('2026-08-01T00:00:00Z')
  for (let i = 0; i < n; i++) {
    fs.writeFileSync(path.join(dir, `f${i}.txt`), `${i}\n`)
    const when = new Date(base + i * dayStep * 86_400_000).toISOString()
    execFileSync('git', ['-C', dir, 'add', '-A'], { stdio: 'pipe' })
    execFileSync('git', ['-C', dir, 'commit', '-q', '-m', `c${i}`], {
      stdio: 'pipe',
      env: {
        ...process.env,
        GIT_AUTHOR_NAME: 'T',
        GIT_AUTHOR_EMAIL: 't@example.com',
        GIT_COMMITTER_NAME: 'T',
        GIT_COMMITTER_EMAIL: 't@example.com',
        GIT_AUTHOR_DATE: when,
        GIT_COMMITTER_DATE: when,
      },
    })
    shas.push(git(dir, ['rev-parse', 'HEAD']))
  }
  return { dir, shas }
}

const A_SHA = 'a'.repeat(40)
const B_SHA = 'b'.repeat(40)

function fakeDocker(opts: {
  sha?: string | null
  diff?: string[]
  execThrows?: boolean
} = {}) {
  return {
    execInContainer: vi.fn(async () => {
      if (opts.execThrows) throw new Error('no such container')
      if (opts.sha == null) throw new Error('cat: No such file or directory')
      return opts.sha + '\n'
    }),
    diffContainer: vi.fn(async () => opts.diff ?? []),
  }
}

function target(over: Partial<DriftTarget> = {}): DriftTarget {
  return {
    harnessId: 'h_iris',
    name: 'iris',
    service: 'hermes-iris',
    container: 'hermes-iris',
    composeFile: null,
    running: true,
    ...over,
  }
}

// --- compose parsing -------------------------------------------------------

describe('readComposeService', () => {
  it('reads a long-form build context for a hermes-* service', () => {
    const compose = [
      '# Generated by hermes-swarm-map — agent: iris',
      'services:',
      '  hermes-iris:',
      '    build:',
      '      context: /Users/juni/Documents/GitHub/hermes-agent-mt',
      '      dockerfile: Dockerfile',
      '    container_name: hermes-iris',
      '    restart: unless-stopped',
      'networks:',
      '  default:',
    ].join('\n')
    expect(readComposeService(compose)).toEqual({
      service: 'hermes-iris',
      buildContext: '/Users/juni/Documents/GitHub/hermes-agent-mt',
      containerName: 'hermes-iris',
      image: null,
    })
  })

  it('reads a shorthand build context for a seraph-* service', () => {
    // The whole reason this parser exists instead of reusing
    // readComposeBuildContext, which anchors on `^  hermes-`.
    const compose = [
      'services:',
      '  seraph-doer:',
      '    build: /Users/juni/Documents/GitHub/hermes-agent-mt',
      '    container_name: seraph-doer',
      '    restart: unless-stopped',
    ].join('\n')
    const parsed = readComposeService(compose)
    expect(parsed.service).toBe('seraph-doer')
    expect(parsed.buildContext).toBe('/Users/juni/Documents/GitHub/hermes-agent-mt')
    expect(parsed.containerName).toBe('seraph-doer')
  })

  it('reads an image-only service and reports no build context', () => {
    const compose = ['services:', '  hermes-mare:', '    image: nimblecoorg/hermes-agent-mt:v1'].join('\n')
    expect(readComposeService(compose)).toMatchObject({
      service: 'hermes-mare',
      buildContext: null,
      image: 'nimblecoorg/hermes-agent-mt:v1',
    })
  })

  it('does not mistake a networks: key for a service', () => {
    const compose = [
      'networks:',
      '  default:',
      '    name: hermes',
      'services:',
      '  hermes-iris:',
      '    build: /src',
      '    container_name: hermes-iris',
    ].join('\n')
    const parsed = readComposeService(compose)
    expect(parsed.service).toBe('hermes-iris')
    expect(parsed.buildContext).toBe('/src')
  })

  it('returns nothing for a compose with no services: block', () => {
    expect(readComposeService('networks:\n  default:\n')).toEqual({
      service: null,
      buildContext: null,
      containerName: null,
      image: null,
    })
  })

  it('stops at the next service key rather than bleeding into it', () => {
    const compose = [
      'services:',
      '  hermes-a:',
      '    container_name: hermes-a',
      '  hermes-b:',
      '    build: /elsewhere',
      '    container_name: hermes-b',
    ].join('\n')
    const parsed = readComposeService(compose)
    expect(parsed.service).toBe('hermes-a')
    expect(parsed.containerName).toBe('hermes-a')
    expect(parsed.buildContext).toBeNull()
  })
})

// --- buildSourceHead -------------------------------------------------------

describe('buildSourceHead', () => {
  let root: string
  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-head-'))
  })
  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true })
  })

  it('returns the full HEAD sha, branch and commit time', () => {
    const { dir, shas } = makeRepo(root, 3)
    const head = buildSourceHead(dir)
    expect(head.head).toBe(shas[2])
    expect(head.head).toMatch(/^[0-9a-f]{40}$/)
    expect(head.branch).toBe('main')
    expect(head.error).toBeNull()
    expect(head.headCommittedAt).toBe(Date.parse('2026-08-03T00:00:00Z'))
  })

  it('counts how far the checkout is behind its own upstream', () => {
    const { dir } = makeRepo(root, 4)
    // Stand up a bare "remote", push, then rewind the local branch two commits.
    const remote = path.join(root, 'remote.git')
    execFileSync('git', ['init', '-q', '--bare', '-b', 'main', remote], { stdio: 'pipe' })
    git(dir, ['remote', 'add', 'origin', remote])
    git(dir, ['push', '-q', '-u', 'origin', 'main'])
    git(dir, ['reset', '-q', '--hard', 'HEAD~2'])

    const head = buildSourceHead(dir)
    expect(head.upstream).toBe('origin/main')
    expect(head.behindUpstream).toBe(2)
  })

  it('reports an error (never a sha) for a missing dir', () => {
    const head = buildSourceHead(path.join(root, 'nope'))
    expect(head.head).toBeNull()
    expect(head.error).toContain('does not exist')
  })

  it('reports an error (never a sha) for a non-git dir', () => {
    const plain = fs.mkdtempSync(path.join(root, 'plain-'))
    const head = buildSourceHead(plain)
    expect(head.head).toBeNull()
    expect(head.error).toContain('not a git repo')
  })

  it('does not fetch — behindUpstream reflects only refs already on disk', () => {
    const { dir } = makeRepo(root, 2)
    const remote = path.join(root, 'remote2.git')
    execFileSync('git', ['init', '-q', '--bare', '-b', 'main', remote], { stdio: 'pipe' })
    git(dir, ['remote', 'add', 'origin', remote])
    git(dir, ['push', '-q', '-u', 'origin', 'main'])
    const beforeFetchHead = fs.existsSync(path.join(dir, '.git', 'FETCH_HEAD'))

    // Advance the remote behind the local repo's back via a second clone.
    const other = path.join(root, 'other')
    execFileSync('git', ['clone', '-q', '-b', 'main', remote, other], { stdio: 'pipe' })
    fs.writeFileSync(path.join(other, 'new.txt'), 'x\n')
    git(other, ['add', '-A'])
    git(other, ['commit', '-q', '-m', 'remote-only'])
    git(other, ['push', '-q', 'origin', 'main'])

    // Read-only: we still see 0, because nothing fetched. That is the honest
    // answer for a module that must not touch the network.
    expect(buildSourceHead(dir).behindUpstream).toBe(0)
    expect(fs.existsSync(path.join(dir, '.git', 'FETCH_HEAD'))).toBe(beforeFetchHead)
  })
})

// --- commitGap -------------------------------------------------------------

describe('commitGap', () => {
  let root: string
  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-gap-'))
  })
  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true })
  })

  it('counts commits AND wall-clock age between the two commits', () => {
    // 5 commits, one day apart: HEAD is c4, container built at c0.
    const { dir, shas } = makeRepo(root, 5)
    const g = commitGap(dir, shas[0], shas[4])
    expect(g.commitsBehind).toBe(4)
    expect(g.ageBehindMs).toBe(4 * 86_400_000)
    expect(g.detail).toBeNull()
  })

  it('reports zero-commit gap for the same commit', () => {
    const { dir, shas } = makeRepo(root, 2)
    const g = commitGap(dir, shas[1], shas[1])
    expect(g.commitsBehind).toBe(0)
    expect(g.ageBehindMs).toBe(0)
  })

  it('returns null counts — never zero — when the container commit is unknown here', () => {
    // Unknown must not be reported as "0 behind"; that is the zero-when-unknown
    // misread that makes a stale agent look fine.
    const { dir, shas } = makeRepo(root, 2)
    const g = commitGap(dir, A_SHA, shas[1])
    expect(g.commitsBehind).toBeNull()
    expect(g.ageBehindMs).toBeNull()
    expect(g.detail).toContain('not present in')
  })

  it('flags a diverged/rolled-back source instead of implying a clean N behind', () => {
    const { dir, shas } = makeRepo(root, 3)
    // Source rolls back to c0; the container still runs c2.
    const g = commitGap(dir, shas[2], shas[0])
    expect(g.commitsBehind).toBe(0)
    expect(g.detail).toContain('not an ancestor')
  })
})

// --- container probes ------------------------------------------------------

describe('containerBuildSha', () => {
  it('reads the sha the Dockerfile stamped in', async () => {
    const docker = fakeDocker({ sha: A_SHA })
    await expect(containerBuildSha(docker, 'hermes-iris')).resolves.toBe(A_SHA)
    expect(docker.execInContainer).toHaveBeenCalledWith(
      'hermes-iris',
      ['cat', BUILD_SHA_PATH],
      expect.any(Number),
    )
  })

  it('returns null when the provenance file is absent (pre-build-arg image)', async () => {
    await expect(containerBuildSha(fakeDocker({ sha: null }), 'hermes-iris')).resolves.toBeNull()
  })

  it('returns null for non-sha content rather than trusting it', async () => {
    const docker = { execInContainer: vi.fn(async () => 'unknown\n'), diffContainer: vi.fn(async () => []) }
    await expect(containerBuildSha(docker, 'hermes-iris')).resolves.toBeNull()
  })
})

describe('hotPatched', () => {
  it('is true when agent code under /opt/hermes/agent was modified', async () => {
    const docker = fakeDocker({ diff: ['C /opt', `C ${AGENT_CODE_PATH}`, `C ${AGENT_CODE_PATH}/tools.py`] })
    await expect(hotPatched(docker, 'hermes-iris')).resolves.toBe(true)
  })

  it('is false for bind-mount noise, which every container shows', async () => {
    // Real `docker diff hermes-iris` output — mounts, not hot-patching.
    const docker = fakeDocker({ diff: ['C /opt', 'A /opt/iris', 'A /opt/iris-intake', 'A /opt/iris-state'] })
    await expect(hotPatched(docker, 'hermes-iris')).resolves.toBe(false)
  })

  it('does not match a sibling path that merely shares the prefix', async () => {
    const docker = fakeDocker({ diff: ['A /opt/hermes/agentic-notes'] })
    await expect(hotPatched(docker, 'hermes-iris')).resolves.toBe(false)
  })
})

// --- enumeration -----------------------------------------------------------

function harness(over: Partial<Harness>): Harness {
  return {
    id: 'h_x',
    name: 'x',
    runtime: 'hermes',
    status: 'running',
    health: { errors: 0 },
    persona: '',
    tier: 'individual',
    platform: 'hermes',
    channel: '',
    lastSeen: 0,
    models: [],
    costToday: 0,
    invocations: 0,
    cpu: 0,
    mem: 0,
    tools: [],
    ...over,
  } as Harness
}

describe('driftTargets', () => {
  let root: string
  let composeBaseDir: string

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-enum-'))
    composeBaseDir = path.join(root, 'compose')
    for (const [name, svc] of [
      ['iris', 'hermes-iris'],
      ['seraph-doer', 'seraph-doer'],
      ['seraph-thinker', 'seraph-thinker'],
    ] as const) {
      fs.mkdirSync(path.join(composeBaseDir, name), { recursive: true })
      fs.writeFileSync(
        path.join(composeBaseDir, name, 'docker-compose.yml'),
        ['services:', `  ${svc}:`, '    build: /src/hermes-agent-mt', `    container_name: ${svc}`].join('\n'),
      )
    }
  })
  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true })
  })

  it('includes seraph-* agents that no `docker ps | grep hermes-` would ever find', () => {
    // Only iris is discovered/running. The three seraph services are keyed
    // seraph-* AND have no container — invisible to both halves of a grep.
    const targets = driftTargets({
      harnesses: [harness({ id: 'h_iris', name: 'iris', serviceName: 'hermes-iris', status: 'running' })],
      composeBaseDir,
    })
    expect(targets.map((t) => t.name).sort()).toEqual(['iris', 'seraph-doer', 'seraph-thinker'])
    const doer = targets.find((t) => t.name === 'seraph-doer')!
    expect(doer.running).toBe(false)
    expect(doer.service).toBe('seraph-doer')
    expect(doer.harnessId).toBe(harnessIdForName('seraph-doer'))
  })

  it('does not double-count an agent present in both the registry and compose dirs', () => {
    const targets = driftTargets({
      harnesses: [harness({ id: 'h_iris', name: 'iris', serviceName: 'hermes-iris' })],
      composeBaseDir,
    })
    expect(targets.filter((t) => t.name === 'iris')).toHaveLength(1)
  })

  it('backfills a compose file onto a registry row that has none', () => {
    const targets = driftTargets({
      harnesses: [harness({ id: 'h_iris', name: 'iris', serviceName: 'hermes-iris' })],
      composeBaseDir,
    })
    expect(targets.find((t) => t.name === 'iris')!.composeFile).toBe(
      path.join(composeBaseDir, 'iris', 'docker-compose.yml'),
    )
  })

  it('skips Letta rows — they are Postgres records, not containers', () => {
    const targets = driftTargets({
      harnesses: [
        harness({ id: 'h_letta_a', name: 'letta-a', runtime: 'letta' }),
        harness({ id: 'h_letta_srv', name: 'letta-srv', runtime: 'letta-server' }),
      ],
      composeBaseDir,
    })
    expect(targets.map((t) => t.name)).not.toContain('letta-a')
    expect(targets.map((t) => t.name)).not.toContain('letta-srv')
  })

  it('keeps a registry-only agent with no compose dir', () => {
    const targets = driftTargets({
      harnesses: [harness({ id: 'h_ghost', name: 'ghost', serviceName: 'hermes-ghost', status: 'stopped' })],
      composeBaseDir,
    })
    expect(targets.find((t) => t.name === 'ghost')).toBeTruthy()
    expect(targets.find((t) => t.name === 'ghost')!.running).toBe(false)
  })
})

describe('resolveBuildSourceDir', () => {
  let root: string
  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-src-'))
  })
  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true })
  })

  it('prefers the compose build context over the global setting', () => {
    const cf = path.join(root, 'docker-compose.yml')
    fs.writeFileSync(cf, ['services:', '  seraph-doer:', '    build: /per/agent/src'].join('\n'))
    expect(resolveBuildSourceDir(cf, '/global/src')).toBe('/per/agent/src')
  })

  it('returns null for an image-only compose — nothing local is built', () => {
    const cf = path.join(root, 'docker-compose.yml')
    fs.writeFileSync(cf, ['services:', '  hermes-mare:', '    image: repo/img:tag'].join('\n'))
    expect(resolveBuildSourceDir(cf, '/global/src')).toBeNull()
  })

  it('falls back to the configured dir when there is no compose file', () => {
    expect(resolveBuildSourceDir(null, '/global/src')).toBe('/global/src')
  })
})

// --- state machine ---------------------------------------------------------

describe('driftForTarget', () => {
  const head = (over = {}) => ({
    dir: '/src',
    head: B_SHA,
    branch: 'main',
    upstream: 'origin/main',
    behindUpstream: 0,
    headCommittedAt: 1,
    error: null,
    ...over,
  })

  it('is current when the container sha equals build-source HEAD', async () => {
    const d = await driftForTarget(target(), '/src', {
      docker: fakeDocker({ sha: B_SHA }),
      readHead: () => head(),
    })
    expect(d.state).toBe('current')
    expect(d.hotPatched).toBe(false)
    expect(d.containerSha).toBe(B_SHA)
  })

  it('is behind with a commit AND age delta when the shas differ', async () => {
    const d = await driftForTarget(target(), '/src', {
      docker: fakeDocker({ sha: A_SHA }),
      readHead: () => head(),
      gap: () => ({ commitsBehind: 11, ageBehindMs: 4 * 86_400_000, detail: null }),
    })
    expect(d.state).toBe('behind')
    expect(d.commitsBehind).toBe(11)
    expect(d.ageBehindMs).toBe(4 * 86_400_000)
  })

  it('is unknown-not-running, never current, for a stopped agent', async () => {
    const d = await driftForTarget(target({ running: false }), '/src', {
      docker: fakeDocker({ sha: B_SHA }),
      readHead: () => head(),
    })
    expect(d.state).toBe('unknown-not-running')
    expect(d.state).not.toBe('current')
  })

  it('is unknown-no-provenance, never current, when the container has no build sha', async () => {
    // This is the 2026-08-10 state of every container in the fleet: the
    // Dockerfile declared ARG HERMES_GIT_SHA but nothing passed it.
    const d = await driftForTarget(target(), '/src', {
      docker: fakeDocker({ sha: null }),
      readHead: () => head(),
    })
    expect(d.state).toBe('unknown-no-provenance')
    expect(d.detail).toContain(BUILD_SHA_PATH)
  })

  it('is unknown-no-provenance when the build source cannot be resolved', async () => {
    const d = await driftForTarget(target(), null, { docker: fakeDocker({ sha: B_SHA }) })
    expect(d.state).toBe('unknown-no-provenance')
  })

  it('is unknown-no-provenance when the build source is not a git repo', async () => {
    const d = await driftForTarget(target(), '/src', {
      docker: fakeDocker({ sha: B_SHA }),
      readHead: () => head({ head: null, error: 'build source /src is not a git repo' }),
    })
    expect(d.state).toBe('unknown-no-provenance')
    expect(d.detail).toContain('not a git repo')
  })

  it('reports a hot-patched container even when its sha matches HEAD', async () => {
    // Sha-equal but someone copied files in; the next recreate reverts them.
    const d = await driftForTarget(target(), '/src', {
      docker: fakeDocker({ sha: B_SHA, diff: [`C ${AGENT_CODE_PATH}/tools.py`] }),
      readHead: () => head(),
    })
    expect(d.state).toBe('current')
    expect(d.hotPatched).toBe(true)
    expect(d.detail).toContain('modified after build')
  })
})

describe('fleetDrift', () => {
  let root: string
  let composeBaseDir: string
  let src: string

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'drift-fleet-'))
    composeBaseDir = path.join(root, 'compose')
    src = path.join(root, 'src')
    for (const [name, svc] of [
      ['iris', 'hermes-iris'],
      ['seraph-doer', 'seraph-doer'],
    ] as const) {
      fs.mkdirSync(path.join(composeBaseDir, name), { recursive: true })
      fs.writeFileSync(
        path.join(composeBaseDir, name, 'docker-compose.yml'),
        ['services:', `  ${svc}:`, `    build: ${src}`, `    container_name: ${svc}`].join('\n'),
      )
    }
  })
  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true })
  })

  it('covers running and never-started agents, and marks nothing green by default', async () => {
    const result = await fleetDrift({
      harnesses: [harness({ id: 'h_iris', name: 'iris', serviceName: 'hermes-iris', status: 'running' })],
      composeBaseDir,
      deps: {
        docker: fakeDocker({ sha: A_SHA }),
        readHead: () => ({
          dir: src,
          head: A_SHA,
          branch: 'main',
          upstream: null,
          behindUpstream: null,
          headCommittedAt: 1,
          error: null,
        }),
      },
    })
    expect(result.agents.map((a) => a.name)).toEqual(['iris', 'seraph-doer'])
    expect(result.agents.find((a) => a.name === 'iris')!.state).toBe('current')
    expect(result.agents.find((a) => a.name === 'seraph-doer')!.state).toBe('unknown-not-running')
    expect(result.checkedAt).toBeGreaterThan(0)
  })

  it('resolves each build-source dir once per sweep, not once per agent', async () => {
    const readHead = vi.fn(() => ({
      dir: src,
      head: A_SHA,
      branch: 'main',
      upstream: null,
      behindUpstream: null,
      headCommittedAt: 1,
      error: null,
    }))
    await fleetDrift({
      harnesses: [
        harness({ id: 'h_iris', name: 'iris', serviceName: 'hermes-iris', status: 'running' }),
        harness({ id: 'h_mare', name: 'mare', serviceName: 'hermes-mare', status: 'running' }),
      ],
      composeBaseDir,
      fallbackHermesDir: src,
      deps: { docker: fakeDocker({ sha: A_SHA }), readHead },
    })
    expect(readHead).toHaveBeenCalledTimes(1)
  })

  it('end-to-end against a real git repo: 4 commits and 4 days behind', async () => {
    const { dir, shas } = makeRepo(root, 5)
    fs.writeFileSync(
      path.join(composeBaseDir, 'iris', 'docker-compose.yml'),
      ['services:', '  hermes-iris:', `    build: ${dir}`, '    container_name: hermes-iris'].join('\n'),
    )
    const result = await fleetDrift({
      harnesses: [harness({ id: 'h_iris', name: 'iris', serviceName: 'hermes-iris', status: 'running' })],
      composeBaseDir,
      deps: { docker: fakeDocker({ sha: shas[0] }) },
    })
    const iris = result.agents.find((a) => a.name === 'iris')!
    expect(iris.state).toBe('behind')
    expect(iris.commitsBehind).toBe(4)
    expect(iris.ageBehindMs).toBe(4 * 86_400_000)
    expect(iris.sourceSha).toBe(shas[4])
  })
})
