import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import fs from 'fs'
import os from 'os'
import path from 'path'

// The migration reads settings (dataDir, defaultImage) and writes the
// normalized defaultImage back through the same service.
const getSettings = vi.fn()
const updateSettings = vi.fn()
vi.mock('@/lib/services', () => ({
  services: { config: { getSettings: (...a: unknown[]) => getSettings(...a), updateSettings: (...a: unknown[]) => updateSettings(...a) } },
}))

import { normalizeImageRef, migrateLegacyImageRefs } from '@/lib/services/image-migration'

// The rename chain, oldest first. ORIGINAL and MID are both DEAD GHCR
// namespaces (packages do not follow repo transfers); only CURRENT receives
// builds.
const ORIGINAL = 'ghcr.io/nimblecoai/hermes-agent-mt'
const MID = 'ghcr.io/nimblecoorg/hermes-agent-mt'
const CURRENT = 'ghcr.io/cyborg-garden/hermes-agent-mt'

// Retained for the migrateLegacyImageRefs suite below, which exercises the
// worst case: an install that never upgraded, still pinned at ORIGINAL.
const LEGACY = ORIGINAL

describe('normalizeImageRef', () => {
  describe('one hop (nimblecoorg → cyborg-garden)', () => {
    it('migrates the bare repo path', () => {
      expect(normalizeImageRef(MID)).toBe(CURRENT)
    })

    it('preserves tags', () => {
      expect(normalizeImageRef(`${MID}:latest`)).toBe(`${CURRENT}:latest`)
      expect(normalizeImageRef(`${MID}:2026-08-06`)).toBe(`${CURRENT}:2026-08-06`)
    })

    it('preserves digests', () => {
      expect(normalizeImageRef(`${MID}@sha256:abc123`)).toBe(`${CURRENT}@sha256:abc123`)
    })
  })

  describe('two hops (nimblecoai → nimblecoorg → cyborg-garden)', () => {
    // The regression this guards: a single-lookup map would move an ORIGINAL
    // ref to MID and stop, which is still a dead namespace. It looks like a
    // successful migration and the fleet stays frozen.
    it('walks the whole chain for the bare repo path', () => {
      expect(normalizeImageRef(ORIGINAL)).toBe(CURRENT)
      expect(normalizeImageRef(ORIGINAL)).not.toBe(MID)
    })

    it('preserves tags across both hops', () => {
      expect(normalizeImageRef(`${ORIGINAL}:latest`)).toBe(`${CURRENT}:latest`)
      expect(normalizeImageRef(`${ORIGINAL}:2026-07-21`)).toBe(`${CURRENT}:2026-07-21`)
    })

    it('preserves digests across both hops', () => {
      expect(normalizeImageRef(`${ORIGINAL}@sha256:abc123`)).toBe(`${CURRENT}@sha256:abc123`)
    })

    it('is a fixed point — re-normalizing changes nothing', () => {
      const once = normalizeImageRef(`${ORIGINAL}:latest`)
      expect(normalizeImageRef(once)).toBe(once)
    })
  })

  it('leaves current refs alone', () => {
    expect(normalizeImageRef(`${CURRENT}:latest`)).toBe(`${CURRENT}:latest`)
    expect(normalizeImageRef(CURRENT)).toBe(CURRENT)
  })

  it('does not match prefixes of longer repo names or substrings', () => {
    for (const dead of [ORIGINAL, MID]) {
      expect(normalizeImageRef(`${dead}-fork:latest`)).toBe(`${dead}-fork:latest`)
      expect(normalizeImageRef(`example.com/${dead}:latest`)).toBe(`example.com/${dead}:latest`)
    }
  })

  it('leaves unrelated images alone', () => {
    expect(normalizeImageRef('ollama/ollama')).toBe('ollama/ollama')
    expect(normalizeImageRef('ghcr.io/jo-inc/camofox-browser:1.13.0')).toBe('ghcr.io/jo-inc/camofox-browser:1.13.0')
  })
})

// Minimal but realistic generated compose — matches the shape
// readComposeImage/setComposeImage parse (4-space image line under the
// 2-space hermes-<name> service key).
function composeFixture(agent: string, image: string): string {
  return `# Generated by hermes-swarm-map — agent: ${agent}
services:
  hermes-${agent}:
    image: ${image}
    container_name: hermes-${agent}
    restart: unless-stopped
    env_file:
      - /home/u/.hermes-${agent}/.env
`
}

describe('migrateLegacyImageRefs', () => {
  let tmp: string

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'img-migration-'))
    getSettings.mockReset()
    updateSettings.mockReset()
  })

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true, force: true })
  })

  function writeCompose(agent: string, image: string): string {
    const dir = path.join(tmp, 'compose', agent)
    fs.mkdirSync(dir, { recursive: true })
    const p = path.join(dir, 'docker-compose.yml')
    fs.writeFileSync(p, composeFixture(agent, image), 'utf-8')
    return p
  }

  it('rewrites legacy defaultImage in settings and legacy compose files', () => {
    // settings pinned at the ORIGINAL namespace — the two-hop case, end to end
    // through the real file layer.
    getSettings.mockReturnValue({ dataDir: tmp, defaultImage: `${LEGACY}:latest` })
    const originalPath = writeCompose('chur-bot', `${ORIGINAL}:latest`)
    const midPath = writeCompose('mid-agent', `${MID}:latest`)
    const currentPath = writeCompose('pmf', `${CURRENT}:latest`)

    const result = migrateLegacyImageRefs()

    expect(updateSettings).toHaveBeenCalledWith({ defaultImage: `${CURRENT}:latest` })
    expect(result.settingsChanged).toBe(true)
    // both dead namespaces heal in a single pass; order is readdir-dependent
    expect(result.composeMigrated.sort()).toEqual([originalPath, midPath].sort())
    expect(result.composeFailed).toEqual([])

    for (const p of [originalPath, midPath]) {
      const content = fs.readFileSync(p, 'utf-8')
      expect(content).toContain(`image: ${CURRENT}:latest`)
      expect(content).not.toContain('nimblecoai')
      expect(content).not.toContain('nimblecoorg')
    }
    // untouched file stays byte-identical
    expect(fs.readFileSync(currentPath, 'utf-8')).toBe(composeFixture('pmf', `${CURRENT}:latest`))
  })

  it('is idempotent', () => {
    getSettings.mockReturnValue({ dataDir: tmp, defaultImage: `${CURRENT}:latest` })
    const p = writeCompose('chur-bot', `${LEGACY}:latest`)

    const first = migrateLegacyImageRefs()
    expect(first.composeMigrated).toEqual([p])

    const second = migrateLegacyImageRefs()
    expect(second.settingsChanged).toBe(false)
    expect(second.composeMigrated).toEqual([])
    expect(updateSettings).not.toHaveBeenCalled()
  })

  it('skips local-build composes and survives a missing compose dir', () => {
    getSettings.mockReturnValue({ dataDir: tmp })
    const dir = path.join(tmp, 'compose', 'dev-agent')
    fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(
      path.join(dir, 'docker-compose.yml'),
      `services:\n  hermes-dev-agent:\n    build:\n      context: /home/u/hermes-agent-mt\n`,
      'utf-8',
    )
    expect(migrateLegacyImageRefs().composeMigrated).toEqual([])

    fs.rmSync(path.join(tmp, 'compose'), { recursive: true, force: true })
    expect(() => migrateLegacyImageRefs()).not.toThrow()
  })

  it('never throws when settings access fails', () => {
    getSettings.mockImplementation(() => { throw new Error('boom') })
    expect(() => migrateLegacyImageRefs()).not.toThrow()
  })
})
