/**
 * Pure templating for the create-new deploy flow: the agent `.env` body and the
 * standalone docker-compose. Extracted from app/api/setup/deploy/route.ts so the
 * templating is unit-testable and the route stays orchestration-only.
 */
import { hsmBaseUrl } from './hsm-url'
import { anthropicEnvVarForValue } from './keys'
import { ollamaSidecar, stateInitService, stateVolumeBlock, stateVolumeName } from './harness-compose'
import { assertNoNewline } from '@/lib/env-helpers'

export function generateEnvContent(params: {
  name: string
  port: number
  provider: string
  primaryModel: string
  fallbackModel?: string
  llmKey?: string
  bundledOllama?: boolean
  mattermostUrl?: string
  mattermostToken?: string
  telegramToken?: string
  discordToken?: string
  slackBotToken?: string
  slackAppToken?: string
  signalPhone?: string
  githubToken?: string
  braveKey?: string
  notionKey?: string
  googleClientId?: string
  googleClientSecret?: string
  browserEnabled?: boolean
  /**
   * Letta-brain "door" wiring (B1 contract): when set, the gateway forwards
   * each turn to this Letta agent over REST. Var names must match exactly what
   * gateway/letta_brain.py reads: LETTA_BRAIN_URL, LETTA_BRAIN_AGENT_ID,
   * LETTA_BRAIN_API_KEY (optional).
   */
  lettaBrain?: { url: string; agentId: string; apiKey?: string }
}): string {
  const { name, port, provider, llmKey, bundledOllama, mattermostUrl, mattermostToken, telegramToken, discordToken, slackBotToken, slackAppToken, signalPhone, githubToken, braveKey, notionKey,
    googleClientId, googleClientSecret, browserEnabled, lettaBrain } = params

  // Every user-supplied string below is spliced onto its own `.env` line. A
  // newline in any of them would inject extra env lines — including overriding
  // the secure-default policy block emitted above the tokens (F10). Reject.
  for (const [field, value] of Object.entries({
    name, provider, llmKey, mattermostUrl, mattermostToken, telegramToken,
    discordToken, slackBotToken, slackAppToken, signalPhone, githubToken, braveKey, notionKey,
    googleClientId, googleClientSecret,
  })) {
    if (typeof value === 'string') assertNoNewline(value, field)
  }
  if (lettaBrain) {
    assertNoNewline(lettaBrain.url, 'lettaBrain.url')
    assertNoNewline(lettaBrain.agentId, 'lettaBrain.agentId')
    if (typeof lettaBrain.apiKey === 'string') assertNoNewline(lettaBrain.apiKey, 'lettaBrain.apiKey')
  }

  const providerKeyMap: Record<string, string> = {
    anthropic: 'ANTHROPIC_API_KEY',
    openrouter: 'OPENROUTER_API_KEY',
    google: 'GOOGLE_API_KEY',
    bedrock: 'AWS_BEARER_TOKEN_BEDROCK',
    zai: 'GLM_API_KEY',
  }

  // Anthropic credentials route to ANTHROPIC_API_KEY or ANTHROPIC_TOKEN by value
  // shape (see anthropicEnvVarForValue) — a bearer token in ANTHROPIC_API_KEY
  // produces a conflicting dual-header request the API rejects.
  const keyVar = provider === 'anthropic' && llmKey
    ? anthropicEnvVarForValue(llmKey)
    : providerKeyMap[provider]
  const keyLine = keyVar && llmKey ? `${keyVar}=${llmKey}` : keyVar ? `${keyVar}=` : '# No API key needed (local/ollama)'

  // Host-GPU ollama (default) points at the host daemon; bundled mode points at
  // the in-compose `ollama-<name>` sidecar (see generateAgentCompose).
  const ollamaLine = (provider === 'ollama' || provider === 'custom')
    ? (bundledOllama
        ? `OLLAMA_BASE_URL=http://ollama-${name}:11434/v1`
        : `OLLAMA_BASE_URL=http://host.docker.internal:11434/v1`)
    : null

  const lines = [
    `# Hermes Agent: ${name}`,
    `# Generated by hermes-swarm-map`,
    '',
    keyLine,
    `API_SERVER_PORT=${port}`,
    '',
    `# Platform integration`,
  ]
  if (ollamaLine) lines.push(ollamaLine)

  if (mattermostUrl) {
    lines.push(`MATTERMOST_URL=${mattermostUrl}`)
  } else {
    lines.push(`# MATTERMOST_URL=`)
  }
  if (mattermostToken) {
    lines.push(`MATTERMOST_TOKEN=${mattermostToken}`)
  } else {
    lines.push(`# MATTERMOST_TOKEN=`)
  }
  if (mattermostUrl || mattermostToken) {
    lines.push(`MATTERMOST_ALLOWED_USERS=`)
    lines.push(`MATTERMOST_ALLOWED_CHANNELS=`)
  } else {
    lines.push(`# MATTERMOST_ALLOWED_USERS=`)
    lines.push(`# MATTERMOST_ALLOWED_CHANNELS=`)
  }
  if (telegramToken) {
    lines.push(`TELEGRAM_BOT_TOKEN=${telegramToken}`)
  } else {
    lines.push(`# TELEGRAM_BOT_TOKEN=`)
  }
  if (discordToken) {
    lines.push(`DISCORD_BOT_TOKEN=${discordToken}`)
    lines.push(`DISCORD_ALLOWED_USERS=`)
    // '0' — not empty. The adapter reads an EMPTY channel allowlist as "no channel
    // gate at all", so an empty value means the bot answers in every channel the
    // moment a user is added to the allowlist above. A snowflake is never '0', so
    // this denies until the operator scopes the agent deliberately.
    lines.push(`DISCORD_ALLOWED_CHANNELS=0`)
    lines.push(`DISCORD_REQUIRE_MENTION=true`)
    // Org policy: anyone in an admin-approved channel may talk to the bot
    // (union with the user allowlist; threads inherit their parent channel).
    // Inert until channels are actually approved — the '0' deny sentinel above
    // parses to no explicit ids, and '*' is never honored as a grant, so this
    // cannot open an agent by itself.
    lines.push(`DISCORD_CHANNEL_SCOPED_ACCESS=true`)
    // Explicit: this check runs BEFORE the user allowlist and skips it entirely
    // when it permits a bot, so it must not be left to an implicit default.
    lines.push(`DISCORD_ALLOW_BOTS=none`)
    // Org policy (2026-08-05): even when ALLOW_BOTS is opened to 'mentions',
    // a bot sender must carry a LITERAL inline @mention — a reply-ping alone
    // does not trigger the agent. Inert while ALLOW_BOTS=none; seeded here so
    // opening bot access later inherits the strict posture by default.
    lines.push(`DISCORD_BOTS_REQUIRE_INLINE_MENTION=true`)
    // Org policy (2026-10-06): @mention required inside threads too. The
    // adapter default (false) lets a bot answer every message in any thread it
    // has joined — the #bounties-work incident. Seeded on BOTH creation paths
    // (ensurePolicyDefaults mirrors it) so they cannot drift.
    lines.push(`DISCORD_THREAD_REQUIRE_MENTION=true`)
  } else {
    lines.push(`# DISCORD_BOT_TOKEN=`)
    lines.push(`# DISCORD_ALLOWED_USERS=`)
    lines.push(`# DISCORD_ALLOWED_CHANNELS=`)
  }
  if (slackBotToken && slackAppToken) {
    lines.push(`SLACK_BOT_TOKEN=${slackBotToken}`)
    lines.push(`SLACK_APP_TOKEN=${slackAppToken}`)
    lines.push(`SLACK_ALLOWED_USERS=`)
    lines.push(`SLACK_ALLOWED_CHANNELS=`)
    lines.push(`SLACK_REQUIRE_MENTION=true`)
  } else {
    lines.push(`# SLACK_BOT_TOKEN=`)
    lines.push(`# SLACK_APP_TOKEN=`)
    lines.push(`# SLACK_ALLOWED_USERS=`)
    lines.push(`# SLACK_ALLOWED_CHANNELS=`)
  }
  if (signalPhone) {
    lines.push(`SIGNAL_HTTP_URL=http://host.docker.internal:8080`)
    lines.push(`SIGNAL_ACCOUNT=${signalPhone}`)
    lines.push(`# SIGNAL_ALLOWED_USERS= (empty = no DMs; add phone numbers to allow, or * for all)`)
    lines.push(`# SIGNAL_GROUP_ALLOWED_USERS= (empty = no groups; add group IDs to allow, or * for all)`)
  } else {
    lines.push(`# SIGNAL_HTTP_URL=http://host.docker.internal:8080`)
    lines.push(`# SIGNAL_ACCOUNT=`)
  }

  // Web extraction (self-hosted Firecrawl — no API key needed)
  lines.push('')
  lines.push(`# Web extraction (self-hosted Firecrawl)`)
  lines.push(`FIRECRAWL_API_URL=http://host.docker.internal:3002`)

  // Swarm Map policy URL — allows agents to query their own harness config
  const hsmUrl = hsmBaseUrl()
  lines.push('')
  lines.push(`# HSM policy endpoint`)
  lines.push(`HSM_URL=${hsmUrl}`)
  lines.push(`SWARM_MAP_POLICY_URL=${hsmUrl}`)

  // Baseline agent identity & memory scoping
  lines.push('')
  lines.push(`# Agent identity`)
  lines.push(`HOME=/opt/data`)
  lines.push(`HERMES_AGENT_NAME=${name}`)
  lines.push(`HERMES_HOME_CHANNEL=`)

  // Policy defaults (secure by default)
  lines.push('')
  // (HERMES_DM_POLICY / HERMES_APPROVAL_ADMIN_ONLY / HERMES_MEMORY_SCOPE used
  // to be written here. No runtime code reads them — base package v1 dropped
  // them so nobody mistakes them for guards.)
  lines.push(`# Policy defaults (secure by default)`)
  lines.push(`SIGNAL_REQUIRE_MENTION=true`)
  lines.push(`TELEGRAM_REQUIRE_MENTION=true`)
  lines.push(`MATTERMOST_REQUIRE_MENTION=true`)
  lines.push(`SIGNAL_OBSERVE_UNMENTIONED=true`)
  lines.push(`MATTERMOST_OBSERVE_UNMENTIONED=true`)
  lines.push(`TELEGRAM_OBSERVE_UNMENTIONED_GROUP_MESSAGES=true`)
  lines.push(`SIGNAL_GROUP_INVITE_POLICY=approved-only`)
  // Slack channel policy: approved-only means an empty SLACK_ALLOWED_CHANNELS
  // approves NO channels, so a freshly deployed agent responds in none until the
  // operator approves them (matches the admin-approval security model). The Hermes
  // runtime treats allow-all + empty as "respond everywhere" — the unsafe default
  // we're locking down here.
  lines.push(`SLACK_CHANNEL_POLICY=approved-only`)
  // Browser tools (Camofox)
  if (browserEnabled) {
    lines.push('')
    lines.push('# Browser tools (Camofox)')
    lines.push('CAMOFOX_URL=http://host.docker.internal:9377')
  }
  // Letta brain (door mode, B1 contract): the gateway detects these vars and
  // forwards each turn to the Letta agent instead of running its own loop.
  if (lettaBrain) {
    lines.push('')
    lines.push(`# Letta brain (door mode)`)
    lines.push(`LETTA_BRAIN_URL=${lettaBrain.url}`)
    lines.push(`LETTA_BRAIN_AGENT_ID=${lettaBrain.agentId}`)
    if (lettaBrain.apiKey) lines.push(`LETTA_BRAIN_API_KEY=${lettaBrain.apiKey}`)
  }
  if (googleClientId || googleClientSecret) {
    lines.push('')
    lines.push('# Google OAuth client (read by google-multiplayer-mcp via the mcp_servers env block)')
    if (googleClientId) lines.push(`GOOGLE_CLIENT_ID=${googleClientId}`)
    if (googleClientSecret) lines.push(`GOOGLE_CLIENT_SECRET=${googleClientSecret}`)
  }
  if (githubToken || braveKey || notionKey) {
    lines.push('')
    lines.push('# Optional integrations')
    if (githubToken) {
      lines.push(`GITHUB_TOKEN=${githubToken}`)
      // The github MCP server reads GITHUB_PERSONAL_ACCESS_TOKEN. Write it as a
      // literal here (via env_file) — do NOT set it in the compose `environment:`
      // block, which resolves ${GITHUB_TOKEN} from the empty process env and, at
      // higher precedence than env_file, would blank it. Literal mirrors the llm key.
      lines.push(`GITHUB_PERSONAL_ACCESS_TOKEN=${githubToken}`)
    }
    if (braveKey) {
      // BRAVE_SEARCH_API_KEY is the var the runtime actually reads —
      // plugins/web/brave_free/provider.py probes only that name, and so does
      // the auto-detect table in tools/web_tools.py. Writing BRAVE_API_KEY
      // alone (the historic name) meant a wizard-supplied Brave key was
      // invisible to the agent: brave-free reported itself unavailable, and a
      // config pinned to it fell through to whatever else happened to have a
      // key. Both names are written — the canonical one for the runtime, the
      // legacy one for anything outside it that may still read it.
      lines.push(`BRAVE_SEARCH_API_KEY=${braveKey}`)
      lines.push(`BRAVE_API_KEY=${braveKey}`)
    }
    if (notionKey) {
      // Write ONLY the canonical NOTION_API_KEY (the var the keys registry
      // manages for rotation/revocation). The notion MCP server reads
      // NOTION_TOKEN, but that's mapped from NOTION_API_KEY in the config.yaml
      // mcp_servers env block — so there's a single source of truth. Writing a
      // second NOTION_TOKEN literal here would go stale on key rotation/unassign
      // (the dashboard only touches NOTION_API_KEY), leaving a revoked token live.
      lines.push(`NOTION_API_KEY=${notionKey}`)
    }
  }

  return lines.join('\n') + '\n'
}

export function generateAgentCompose(
  slug: string,
  port: number,
  agentDataDir: string,
  imageOrBuild: { image: string } | { build: string },
  options?: {
    googleMcpDir?: string
    githubMcpEnabled?: boolean
    bundledOllama?: boolean
    ollamaImage?: string
    memory?: string
    cpus?: string
  },
): string {
  // githubMcpEnabled is accepted for API compatibility but no longer used here:
  // the github MCP token is delivered via the agent .env (env_file), not a compose
  // `environment:` override (which resolves from the empty process env and blanks it).
  const { googleMcpDir, bundledOllama, ollamaImage, memory, cpus } = options ?? {}
  const sourceBlock = 'image' in imageOrBuild
    ? `    image: ${imageOrBuild.image}`
    : `    build:\n      context: ${imageOrBuild.build}\n      dockerfile: Dockerfile`

  // Google OAuth callback port — offset from agent's main port to avoid conflicts
  // e.g. agent on 8642 → OAuth on 9095, agent on 8652 → OAuth on 9105
  const oauthPort = port + 453  // 8642 + 453 = 9095 (avoids collisions with agent port range)
  const googleMcpPorts = googleMcpDir
    ? `      - published: ${oauthPort}\n        target: 8095   # Google OAuth callback (google-multiplayer-mcp auth flow)\n`
    : ``

  const googleMcpVolumes = googleMcpDir
    ? `      - ${googleMcpDir}:/opt/google-multiplayer-mcp:ro\n      - ${agentDataDir}/google-tokens:/opt/google/tokens\n`
    : ``

  // Optional bundled ollama sidecar (CPU, tiny model) — shares the default named
  // network, so hermes reaches it at http://ollama-<slug>:11434 (matches the env
  // OLLAMA_BASE_URL written in bundled mode). Reuses the same sidecar definition
  // as the standalone generator (harness-compose.ts) — single source of truth.
  const ollamaBlock = bundledOllama ? ollamaSidecar(slug, agentDataDir, ollamaImage, '') : ''
  // One-shot DB-migration init service (named-volume symlink pattern, #204 PR2)
  // — same shared definition as the standalone generator, single source of truth.
  const initBlock = stateInitService(slug, agentDataDir, sourceBlock)
  // Always emitted (init gate); map form so the conditional ollama entry merges.
  const hermesDepends =
    `    depends_on:\n` +
    (bundledOllama ? `      ollama-${slug}:\n        condition: service_healthy\n` : '') +
    `      state-init-${slug}:\n        condition: service_completed_successfully\n`

  return `# Generated by hermes-swarm-map — agent: ${slug}
services:
${initBlock}${ollamaBlock}  hermes-${slug}:
${sourceBlock}
    container_name: hermes-${slug}
    restart: unless-stopped
${hermesDepends}    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ${agentDataDir}/.env
    ports:
      - published: ${port}
        target: 8642
${googleMcpPorts}    volumes:
      - ${agentDataDir}:/opt/data
      - ${stateVolumeName(slug)}:/state
${googleMcpVolumes}    command: gateway
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:false
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
      # s6-overlay execs its init from /run; a bare tmpfs is mounted noexec,
      # which makes the agent restart-loop at boot (exit 126). Mount it exec.
      - /run:exec
    deploy:
      resources:
        limits:
          memory: ${memory ?? '2G'}
          cpus: '${cpus ?? '2.0'}'

networks:
  default:
    name: hermes-${slug}
${stateVolumeBlock(slug)}`
}
