export type HabitatTier = 'individual' | 'team' | 'org' | 'orgpublic' | 'public'

export type HarnessStatus = 'running' | 'idle' | 'stopped' | 'error' | 'restarting'

export type CacheState = 'warm' | 'cold' | 'stale'

// quick:    docker compose restart — restarts the process, does NOT reload env_file
// recreate: up -d --force-recreate — recreates the container, reloads env_file (no image build)
// rebuild:  up -d --build --force-recreate — rebuilds image + recreates
// purge:    build --no-cache + up -d --force-recreate — full from-scratch rebuild
export type RestartMode = 'quick' | 'recreate' | 'rebuild' | 'purge'

export type Harness = {
  id: string
  name: string
  // 'letta'        — a Letta agent (a row in the Letta server's Postgres, not a
  //                  container). Managed over REST via AgentResourceProvider.
  // 'letta-server' — the Letta server itself, a real container-backed harness
  //                  (docker/letta-compose.yml, service `letta`) that hosts N
  //                  'letta' agents as children (parentId = its id).
  runtime: 'hermes' | 'claude-code-proxy' | 'custom' | 'letta' | 'letta-server'
  parentId?: string
  status: HarnessStatus
  health: { errors: number; errorMsg?: string }
  persona: string
  tier: HabitatTier
  platform: string
  channel: string
  lastSeen: number
  models: string[]
  // null = unknown (harness migrated to a named DB volume, snapshot not yet
  // exported) — distinct from 0, which means "no usage". Render as '—', not $0.
  costToday: number | null
  invocations: number | null
  cpu: number
  mem: number
  tools: string[]
  // The host port this agent's compose publishes (API_SERVER_PORT). Persisted so
  // port allocation has an authoritative source — `channel` is only a display
  // string (":8642") and live Docker state is absent for not-yet-started agents.
  apiPort?: number
  cacheState?: CacheState
  cacheAge?: number
  composeFile?: string
  serviceName?: string
  // CD: the image ref this agent is intentionally pinned to (digest or tag), and
  // the digest it last resolved to — for "update available" surfacing + rollback.
  pinnedImageRef?: string
  lastKnownDigest?: string
  // Per-harness compose resource limits (deploy.resources.limits). Persisted on
  // the overlay and re-rendered into the compose on change. Memory-heavy
  // harnesses OOM-kill under the hardcoded 2G default; raise these to fit the job.
  resources?: { memory?: string; cpus?: string }
  // Explicit per-surface admin list, keyed by platform ('signal', 'telegram', …),
  // holding the runtime's native identity keys (Signal UUID/phone, Telegram
  // numeric id, …). This is HSM-side policy the swarm_map_policy plugin queries
  // live (no container recreate needed). When a platform is ABSENT here, the
  // admin set falls back to that surface's DM allowlist ({PLATFORM}_ALLOWED_USERS
  // in the agent .env) — so an agent with no explicit role config behaves exactly
  // as before. See lib/services/surface-admins.ts.
  surfaceAdmins?: Record<string, string[]>
  // Bind mounts this agent needs beyond the standard data dir + state volume,
  // and env vars naming them. Persisted on the overlay and re-rendered into the
  // compose on every regeneration.
  //
  // This exists because the alternative is hand-editing a generated file. An
  // agent that needs a host path (an approval-gate spool, a shared corpus, a
  // socket) got its mount added by hand under the "# Generated by
  // hermes-swarm-map" header, and the next regeneration silently dropped it.
  // Silently is the problem: the container comes up healthy and the capability
  // is just gone, so the failure surfaces later as the agent behaving as though
  // a subsystem does not exist. Config that survives regeneration is the fix.
  extraMounts?: ExtraMount[]
  // Extra environment variables rendered into the compose `environment:` block.
  // Keep secrets OUT of here — this lands in a file that is regenerated and
  // often committed alongside deploy config. Secrets belong in the agent's
  // .env (env_file), which this never touches.
  extraEnv?: Record<string, string>
  // "Track the newest version of this model" — keyed by "provider/model"
  // exactly as the entry appears in the agent's fallback_providers (e.g.
  // "openrouter/z-ai/glm-5.2"). true = the model-update scheduler may rotate
  // this entry to its version successor (in 'apply' mode) and the key is
  // rotated with it. Absent/false = report only. Never set for ollama.
  modelTracking?: Record<string, boolean>
}

/** Global policy for the model-update scheduler (Settings.modelAutoUpdate). */
export type ModelAutoUpdateSettings = {
  enabled: boolean // default false — no background checks until switched on
  mode: 'notify' | 'apply' // 'notify' = report only; 'apply' = rewrite tracked cascades
  intervalHours: number // default 24
  maxPriceMultiplier: number // default 1.5 — a successor costing more than this × current is never applied
}

/**
 * One host→container bind mount on an agent's hermes service.
 *
 * `mode` defaults to 'ro'. That default is deliberate: a mount is the main way
 * an agent's blast radius grows, and read-only is the version that cannot
 * corrupt host state. Write access should be a thing someone typed.
 */
export type ExtraMount = {
  hostPath: string
  containerPath: string
  mode?: 'ro' | 'rw'
  /** Why this mount exists. Rendered as a comment above it in the compose. */
  note?: string
}

export type Surface = {
  id: string
  platform: string
  name: string
  status: 'connected' | 'available' | 'planned'
  config: Record<string, string>
  harnessIds: string[]
}

export type Key = {
  id: string
  provider: string
  name?: string
  // Explicit target .env var. Custom-provider keys use this (or fall back to a
  // name-derived var) since they have no fixed provider→var mapping.
  envVar?: string
  // Non-secret companion value for providers whose credential is a pair.
  // Bluesky: the account handle/DID, emitted as BLUESKY_IDENTIFIER alongside
  // the app password (the key's actual secret value → BLUESKY_APP_PASSWORD).
  identifier?: string
  maskedValue: string
  assignedTo: string[]
  budgetUsd?: number
  health: 'good' | 'warning' | 'expired'
}

export type KeyInput = {
  provider: string
  value: string
  name?: string
  envVar?: string
  identifier?: string
  budgetUsd?: number
}

export type Tool = {
  id: string
  name: string
  source: 'builtin' | 'mcp' | 'custom'
  risk: 1 | 2 | 3 | 4 | 5
  allowedTiers: HabitatTier[]
  reviewed: boolean
  description: string
}

export type MemoryScope = {
  id: string
  name: string
  strategy: 'siloed-runtime' | 'tag-gated'
  members: string[]
  sizeMb: number
  tier: HabitatTier
}

export type Model = {
  id: string
  name: string
  vendor: string
  costClass: 'free' | 'low' | 'medium' | 'high' | 'local'
  accessTier: 'open' | 'admin'
  notes?: string
}

export type Person = {
  id: string
  handle: string
  role: 'admin' | 'community'
  surfaces: string[]
}

export type AuditEntry = {
  ts: number
  who: string
  what: string
  target: string
  meta?: Record<string, unknown>
}

// Named cascade library (lib/services/cascades.ts). A saved, portable
// fallback_providers shape. Never carries api_key.
export type CascadeLibraryEntry = {
  provider: string
  model: string
  base_url?: string
}

export type CascadeRecord = {
  name: string
  chain: CascadeLibraryEntry[]
  createdAt: number
  updatedAt: number
  sourceHarness?: string
}

export type Settings = {
  hermesDir: string  // directory to scan for docker-compose*.yml files
  dataDir: string
  theme: 'light' | 'dark'
  composeFiles: string[]  // explicit list of compose files; empty = auto-scan hermesDir
  onboarded?: boolean
  defaultImage?: string  // Default Docker image for new agents (default: nousresearch/hermes-agent:latest)
  useLocalBuild?: boolean  // Build from hermesDir instead of pulling upstream image
  localApiEnabled?: boolean  // Expose harnesses at a local API endpoint
  localApiPort?: number  // Port for the local API (default 8600)
  vncBindHost?: string  // Host interface for the VPN-mode VNC port (default '127.0.0.1'); set to a Tailscale address for remote human CAPTCHA escalation
  controlBindHost?: string  // Host interface for the VPN-mode Camofox control port 9377 (default '127.0.0.1', unauthenticated browser control); set to a Tailscale address only for remote control
  modelAutoUpdate?: ModelAutoUpdateSettings  // model freshness / "track newest version" policy (see lib/services/model-update-scheduler.ts)
}
