/**
 * The load-bearing claim of scripts/backfill-extra-mounts.mjs is:
 *
 *   "record these mounts in extraMounts and a compose regeneration will render
 *    them back instead of dropping them."
 *
 * These tests check that claim by CONTENT — they run the planner over a fixture
 * HSM home, feed the extraMounts it produces to the real
 * `generateStandaloneCompose`, and assert the mounts come out the other side.
 * A test that only asserted "the JSON gained a key" would pass while the
 * capability stayed broken, which is the shape of failure this whole exercise
 * is about.
 */
import { describe, it, expect, afterEach } from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import type { ExtraMount } from '@/lib/types'
import { generateStandaloneCompose } from '@/lib/services/harness-compose'
import { buildPlan as buildPlanUntyped, applyPlan, readMountScalar as readMountScalarUntyped, splitMountSpec } from '../backfill-extra-mounts.mjs'

const readMountScalar = readMountScalarUntyped as (item: string) => string | null

type Addition = ExtraMount & { mode: 'ro' | 'rw'; _modeImplicit?: boolean }
type AgentRecord = {
  agent: string
  id: string
  service?: string
  existing: ExtraMount[]
  additions: Addition[]
  blockedNoOverlay?: boolean
}
type Plan = { refusals: string[]; warnings: string[]; agents: AgentRecord[] }

const buildPlan = buildPlanUntyped as (opts: { hsmHome: string; only?: string }) => Plan

let home: string

/** A compose file shaped like the fleet's google-MCP agents. */
function googleCompose(agent: string, dataDir: string, mcpDir: string) {
  return `# Generated by hermes-swarm-map — agent: ${agent}
services:
  hermes-${agent}:
    build:
      context: /src
      dockerfile: Dockerfile
    container_name: hermes-${agent}
    volumes:
      - ${dataDir}:/opt/data
      - ${mcpDir}:/opt/google-multiplayer-mcp:ro
      - ${dataDir}/google-tokens:/opt/google/tokens
    command: gateway
`
}

function writeHome(agents: Record<string, string>, overlays: unknown[]) {
  home = fs.mkdtempSync(path.join(os.tmpdir(), 'hsm-backfill-'))
  for (const [name, compose] of Object.entries(agents)) {
    fs.mkdirSync(path.join(home, 'compose', name), { recursive: true })
    fs.writeFileSync(path.join(home, 'compose', name, 'docker-compose.yml'), compose)
  }
  fs.writeFileSync(path.join(home, 'harnesses.json'), JSON.stringify(overlays, null, 2))
  return home
}

afterEach(() => { if (home) fs.rmSync(home, { recursive: true, force: true }) })

describe('backfill planner', () => {
  it('records the google-MCP mounts and leaves the generator-owned ones alone', () => {
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal' }],
    )
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals).toEqual([])
    const rec = plan.agents.find((a: AgentRecord) => a.agent === 'personal')!
    expect(rec.additions.map((m: Addition) => [m.containerPath, m.mode])).toEqual([
      ['/opt/google-multiplayer-mcp', 'ro'],
      ['/opt/google/tokens', 'rw'],
    ])
    // /opt/data is generator-owned and must never be copied in.
    expect(rec.additions.some((m: Addition) => m.containerPath === '/opt/data')).toBe(false)
  })

  it("writes mode explicitly, so docker's rw default is not silently flipped to ExtraMount's ro default", () => {
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal' }],
    )
    const plan = buildPlan({ hsmHome: home })
    const tokens = plan.agents[0].additions.find((m: Addition) => m.containerPath === '/opt/google/tokens')!
    // The compose line is `- /data/personal/google-tokens:/opt/google/tokens`
    // with NO mode. Docker reads that as rw. ExtraMount defaults to ro. If this
    // ever records ro (or omits mode), OAuth token refresh starts failing.
    expect(tokens.mode).toBe('rw')
    expect(Object.prototype.hasOwnProperty.call(tokens, 'mode')).toBe(true)
  })

  it('is idempotent: a second plan over the applied file adds nothing', () => {
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal' }],
    )
    const first = buildPlan({ hsmHome: home })
    fs.writeFileSync(path.join(home, 'harnesses.json'), applyPlan(first))
    const second = buildPlan({ hsmHome: home })
    expect(second.refusals).toEqual([])
    expect(second.agents[0].additions).toEqual([])
  })

  it('never invents an overlay entry for an agent that has none', () => {
    writeHome(
      { orphan: googleCompose('orphan', '/data/orphan', '/src/google-mcp') },
      [],
    )
    const plan = buildPlan({ hsmHome: home })
    expect(plan.agents[0].blockedNoOverlay).toBe(true)
    expect(plan.agents[0].additions).toEqual([])
    expect(JSON.parse(applyPlan(plan))).toEqual([])
    expect(plan.warnings.join('\n')).toMatch(/NO entry in harnesses.json/)
  })

  it('refuses when a recorded mount disagrees with the compose', () => {
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal', extraMounts: [
        { hostPath: '/somewhere/else', containerPath: '/opt/google-multiplayer-mcp', mode: 'ro' },
      ] }],
    )
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals.join('\n')).toMatch(/is recorded as \/somewhere\/else/)
  })

  it('refuses when an existing overlay already targets a generator-owned path', () => {
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal', extraMounts: [
        { hostPath: '/evil', containerPath: '/opt/data', mode: 'rw' },
      ] }],
    )
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals.join('\n')).toMatch(/already targets the generated path \/opt\/data/)
  })

  it('refuses long-syntax mounts rather than skipping them silently', () => {
    const compose = `services:
  hermes-x:
    container_name: hermes-x
    volumes:
      - /data/x:/opt/data
      - type: bind
        source: /host/thing
        target: /opt/thing
    command: gateway
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals.join('\n')).toMatch(/long-syntax mount/)
  })

  it('ignores the state-init sidecar and reads the agent service', () => {
    const compose = `services:
  state-init-x:
    image: busybox
    volumes:
      - /data/x:/opt/data
      - hermes-state-x:/state
  hermes-x:
    container_name: hermes-x
    volumes:
      - /data/x:/opt/data
      - /src/google-mcp:/opt/google-multiplayer-mcp:ro
      - hermes-state-x:/state
    command: gateway
volumes:
  hermes-state-x:
    name: hermes-state-x
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x', serviceName: 'hermes-x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals).toEqual([])
    expect(plan.agents[0].service).toBe('hermes-x')
    expect(plan.agents[0].additions.map((m: Addition) => m.containerPath)).toEqual(['/opt/google-multiplayer-mcp'])
  })
})

describe('YAML comments in the volumes: block', () => {
  // These compose files are hand-edited by definition — that is the premise of
  // the whole script — and a hand-editor annotates. Before readMountScalar(),
  // the comment was split into containerPath, which is not cosmetic: it
  // defeated the GENERATED_TARGETS exact-match guard.

  it('does NOT fold an end-of-line comment into containerPath', () => {
    const compose = `services:
  hermes-x:
    container_name: hermes-x
    volumes:
      - /data/x:/opt/data
      - /src/google-mcp:/opt/google-multiplayer-mcp:ro
      - /data/x/google-tokens:/opt/google/tokens   # OAuth refresh writes here
    command: gateway
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals).toEqual([])
    const tokens = plan.agents[0].additions.find(
      (m: Addition) => m.containerPath === '/opt/google/tokens')
    expect(tokens).toBeDefined()
    expect(tokens!.mode).toBe('rw')
    // The failure mode: '/opt/google/tokens   # OAuth refresh writes here'
    expect(plan.agents[0].additions.map((m: Addition) => m.containerPath))
      .toEqual(['/opt/google-multiplayer-mcp', '/opt/google/tokens'])
  })

  it('still recognises /opt/data as generator-owned when it carries a comment', () => {
    // The dangerous one. A commented /opt/data used to classify as 'extra' and
    // get copied into extraMounts, so the next regeneration rendered /opt/data
    // TWICE and docker refused the compose outright — the exact breakage this
    // script exists to prevent.
    const compose = `services:
  hermes-x:
    container_name: hermes-x
    volumes:
      - /data/x:/opt/data   # agent state, do not move
      - /src/google-mcp:/opt/google-multiplayer-mcp:ro
    command: gateway
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals).toEqual([])
    expect(plan.agents[0].additions.some(
      (m: Addition) => m.containerPath.startsWith('/opt/data'))).toBe(false)
    expect(plan.agents[0].additions.map((m: Addition) => m.containerPath))
      .toEqual(['/opt/google-multiplayer-mcp'])
  })

  it('does not silently skip a volumes: key that carries a comment', () => {
    // `volumes:` failing to match meant inVolumes stayed false and EVERY mount
    // in the block was dropped without a word — zero additions, exit 0, and a
    // human concluding there was nothing to back up.
    const compose = `services:
  hermes-x:
    container_name: hermes-x
    volumes:   # hand-maintained, see runbook
      - /data/x:/opt/data
      - /src/google-mcp:/opt/google-multiplayer-mcp:ro
    command: gateway
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals).toEqual([])
    expect(plan.agents[0].additions.map((m: Addition) => m.containerPath))
      .toEqual(['/opt/google-multiplayer-mcp'])
  })

  it('never attributes one service\'s mounts to another when a service key is unreadable', () => {
    // An unmatched key at service depth used to leave `service` pointing at the
    // PREVIOUS service, so hermes-y's mounts were recorded onto hermes-x.
    // Refusing out loud is the only acceptable outcome.
    const compose = `services:
  hermes-x:
    container_name: hermes-x
    volumes:
      - /data/x:/opt/data
  "hermes y":
    container_name: hermes-y
    volumes:
      - /src/secret:/opt/secret:ro
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.agents[0].additions.map((m: Addition) => m.containerPath))
      .toEqual([])
    expect(JSON.stringify(plan)).not.toContain('/opt/secret')
    // Not attributing the mount is only half of it. hermes-x resolves cleanly
    // here, so without a file-level anomaly buildPlan would return zero
    // refusals and exit 0 for a compose file that visibly had a second service
    // full of mounts — "nothing to back up" as a silent lie. Assert the refusal
    // the comment above promises, so the promise cannot rot away again.
    expect(plan.refusals.join('\n')).toMatch(/unreadable service key at service depth/)
    expect(plan.refusals.join('\n')).toContain('hermes y')
  })

  it('treats a quoted mount as literal and refuses malformed quoting', () => {
    expect(readMountScalar('/a:/b # c')).toBe('/a:/b')
    expect(readMountScalar('"/a:/b # c"')).toBe('/a:/b # c')   // quoted: literal
    expect(readMountScalar("'/a:/b'")).toBe('/a:/b')
    expect(readMountScalar('"/a:/b" # trailing')).toBe('/a:/b')
    expect(readMountScalar('/a#1:/b')).toBe('/a#1:/b')         // no space: literal
    expect(readMountScalar('"/a:/b')).toBeNull()               // unterminated
    expect(readMountScalar('"/a":/b')).toBeNull()              // junk after quote
    expect(readMountScalar('# just a note')).toBe('')          // null list item
  })

  it('refuses, rather than skips, a list item it cannot quote-parse', () => {
    const compose = `services:
  hermes-x:
    container_name: hermes-x
    volumes:
      - /data/x:/opt/data
      - "/src/google-mcp:/opt/google-multiplayer-mcp
    command: gateway
`
    writeHome({ x: compose }, [{ id: 'h_x', name: 'x' }])
    const plan = buildPlan({ hsmHome: home })
    expect(plan.refusals.join('\n')).toMatch(/cannot quote-parse/)
  })
})

describe('splitMountSpec', () => {
  it('reads short syntax and defaults the mode the way docker does', () => {
    expect(splitMountSpec('/a:/b')).toMatchObject({ hostPath: '/a', containerPath: '/b', mode: 'rw', modeImplicit: true })
    expect(splitMountSpec('/a:/b:ro')).toMatchObject({ mode: 'ro', modeImplicit: false })
    expect(splitMountSpec('named-vol:/b')).toMatchObject({ hostPath: 'named-vol' })
  })
  it('refuses anything it cannot vouch for', () => {
    expect(splitMountSpec('type: bind')).toBeNull()   // long syntax
    expect(splitMountSpec('/a:/b:z')).toBeNull()      // bogus mode
    expect(splitMountSpec('/a:relative')).toBeNull()  // non-absolute target
  })
})

describe('the claim: recorded mounts survive regeneration', () => {
  it('re-renders every backfilled mount into a regenerated compose', () => {
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal' }],
    )
    const plan = buildPlan({ hsmHome: home })
    const after = JSON.parse(applyPlan(plan))
    const extraMounts = after[0].extraMounts

    const regenerated = generateStandaloneCompose('personal', 8642, '/data/personal', { extraMounts })

    expect(regenerated).toContain('/src/google-mcp:/opt/google-multiplayer-mcp:ro')
    expect(regenerated).toContain('/data/personal/google-tokens:/opt/google/tokens:rw')
  })

  it('WITHOUT the backfill, the same regeneration drops both mounts — this is the bug', () => {
    const regenerated = generateStandaloneCompose('personal', 8642, '/data/personal', {})
    expect(regenerated).not.toContain('google-multiplayer-mcp')
    expect(regenerated).not.toContain('/opt/google/tokens')
  })

  it('the backfill does NOT restore the rest of a deploy-born compose', () => {
    // Stated as a test so nobody reads the backfill as making regeneration
    // safe. extraMounts carries mounts, and only mounts.
    writeHome(
      { personal: googleCompose('personal', '/data/personal', '/src/google-mcp') },
      [{ id: 'h_personal', name: 'personal' }],
    )
    const plan = buildPlan({ hsmHome: home })
    const extraMounts = JSON.parse(applyPlan(plan))[0].extraMounts
    const regenerated = generateStandaloneCompose('personal', 8642, '/data/personal', { extraMounts })
    // The OAuth callback publish and any read_only/security_opt hardening are
    // NOT recoverable from extraMounts.
    expect(regenerated).not.toContain('8095')
    expect(regenerated).not.toContain('security_opt')
  })
})
