/**
 * Opinionated config.yaml template for new Hermes agents.
 * Shared across all agent creation paths (overlay + full deploy).
 */

import { MODEL_CATALOG } from '../model-catalog'
import { isSurfacePlatform } from '../config-yaml-helpers'

export interface McpServerConfig {
  command?: string
  url?: string
  args?: string[]
  env?: Record<string, string>
}

export function generateDefaultConfig(params: {
  provider: string
  primaryModel: string
  fallbackModel?: string
  browserEnabled?: boolean
  mcpServers?: Record<string, McpServerConfig>
  enabledPlugins?: string[]
  /** Chat surfaces chosen at deploy time — emitted as `platforms.<p>.enabled: true`
   *  so the gateway actually starts them (it skips platforms without that flag). */
  enabledPlatforms?: string[]
  /** web.search_backend. Base package: 'brave-free' when a Brave key is
   *  assigned, the no-key fallback ('ddgs') otherwise. Defaults to brave-free. */
  searchBackend?: string
}): string {
  const { provider, primaryModel, fallbackModel, browserEnabled, mcpServers, enabledPlugins, enabledPlatforms } = params
  const searchBackend = params.searchBackend ?? 'brave-free'
  if (!/^[a-z][a-z0-9-]*$/.test(searchBackend)) {
    throw new Error(`Invalid search backend: ${searchBackend}`)
  }

  // Compression summary_model must be a VALID id served by THIS agent's provider,
  // emitted in litellm `provider/model` form — never a hardcoded foreign provider.
  // Local providers ('ollama'/'custom') are declared as `custom` with a base_url
  // in the model block below, so the summary must use the SAME `custom` prefix and
  // reuse the primary model (the one actually served by the local endpoint) — a
  // catalog 'local' id might not be pulled. Cloud providers use a cheaper
  // 'fallback'/'local' catalog entry, else the caller's fallbackModel, else primary.
  let summaryModel: string
  if (provider === 'ollama' || provider === 'custom') {
    summaryModel = `custom/${primaryModel}`
  } else {
    const catalogEntries = MODEL_CATALOG[provider] ?? []
    const summaryEntry =
      catalogEntries.find((e) => e.tier === 'fallback') ??
      catalogEntries.find((e) => e.tier === 'local')
    const summaryModelId = summaryEntry?.id ?? fallbackModel ?? primaryModel
    summaryModel = `${provider}/${summaryModelId}`
  }

  const fallbackLine = fallbackModel
    ? `  fallback: ${fallbackModel}`
    : `  # fallback: <model>  # uncomment to set a fallback model`

  let mcpBlock = ''
  if (mcpServers && Object.keys(mcpServers).length > 0) {
    mcpBlock = '\n# --- MCP Servers (auto-configured by Swarm Map) ---\nmcp_servers:\n'
    for (const [name, server] of Object.entries(mcpServers)) {
      mcpBlock += `  ${name}:\n`
      if (server.command) mcpBlock += `    command: ${server.command}\n`
      if (server.url) mcpBlock += `    url: ${server.url}\n`
      if (server.args && server.args.length > 0) {
        mcpBlock += `    args:\n`
        for (const arg of server.args) {
          mcpBlock += `      - "${arg}"\n`
        }
      }
      if (server.env && Object.keys(server.env).length > 0) {
        mcpBlock += `    env:\n`
        for (const [key, value] of Object.entries(server.env)) {
          mcpBlock += `      ${key}: "${value}"\n`
        }
      }
    }
  }

  // Only known surface slugs are ever spliced into the file (same posture as
  // assertNoNewline in env-helpers) — reject anything else loudly.
  let platformsBlock = ''
  if (enabledPlatforms && enabledPlatforms.length > 0) {
    platformsBlock = '\n# --- Platforms (chat surfaces the gateway starts) ---\nplatforms:\n'
    for (const p of enabledPlatforms) {
      if (!isSurfacePlatform(p)) {
        throw new Error(`Unknown platform: ${p}`)
      }
      platformsBlock += `  ${p}:\n    enabled: true\n`
    }
  }

  let pluginsBlock = ''
  if (enabledPlugins && enabledPlugins.length > 0) {
    pluginsBlock = '\n# --- Plugins (standalone plugins enabled by Swarm Map) ---\nplugins:\n  enabled:\n'
    for (const name of enabledPlugins) {
      pluginsBlock += `    - ${name}\n`
    }
  }

  return `# Hermes Agent — generated by Swarm Map
# Full reference: https://github.com/NousResearch/hermes-agent/blob/main/cli-config.yaml.example

model:
  provider: ${provider === 'ollama' ? 'custom' : provider}
  default: ${primaryModel}
${provider === 'ollama' || provider === 'custom' ? '  base_url: "http://host.docker.internal:11434/v1"\n' : ''}${fallbackLine}

# --- Context compression (prevents OOM on long conversations) ---
compression:
  enabled: true
  threshold: 0.50
  target_ratio: 0.20
  protect_last_n: 20
  summary_model: "${summaryModel}"

# --- Persistent memory (carries knowledge across sessions) ---
memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 5000
  user_char_limit: 2000
  nudge_interval: 10
  flush_min_turns: 6

# --- Session reset (messaging platforms — prevents runaway token costs) ---
session_reset:
  mode: both
  idle_minutes: 1440
  at_hour: 4

# Shared group session by default (one session per group, sender-name prefixed).
# DMs stay isolated regardless. Set to true for per-person sessions inside a group.
group_sessions_per_user: false

# --- Agent behavior ---
agent:
  max_turns: 60
  verbose: false
  reasoning_effort: "medium"

# --- Voice transcription (pre-installed in Docker) ---
stt:
  enabled: true
  local:
    model: "base"

# --- Text-to-Speech (Edge TTS — free, no API key) ---
tts:
  enabled: true
  default_provider: "edge"
  edge:
    voice: "en-US-AriaNeural"

# --- Web tools ---
# Both keys are set explicitly. Leaving search_backend unset makes the runtime
# auto-detect from whichever API key happens to be present, so the provider an
# agent actually searches with becomes a side effect of .env ordering rather
# than a decision - and it changes silently when a key is added. Names must
# match the runtime's provider registry exactly: brave-free, NOT brave.
web:
  search_backend: ${searchBackend}
  extract_backend: firecrawl

# --- Terminal access ---
terminal:
  backend: "local"
  cwd: "."
  timeout: 180
${browserEnabled ? `
# --- Browser ---
browser:
  inactivity_timeout: 120
  command_timeout: 30
  camofox:
    managed_persistence: false
` : ''}

# --- Skills ---
skills:
  creation_nudge_interval: 15

# --- Display ---
display:
  compact: false
  tool_progress: all
  interim_assistant_messages: true
  streaming: true

# --- Platform toolsets (explicit defaults) ---
platform_toolsets:
  cli: [hermes-cli]
  telegram: [hermes-telegram]
  discord: [hermes-discord]
  signal: [hermes-signal]
  slack: [hermes-slack]
  mattermost: [hermes-mattermost]
${platformsBlock}${pluginsBlock}${mcpBlock}`
}
